### ISSUE TITLE
language: pub or bot or ...?

### ISSUE THREAD

**Issue by ahdinosaur** [peachcloud/meta#7]
at the moment, the colloquial word for an external Scuttlebutt server is a ["pub"](https://www.scuttlebutt.nz/concepts/pub.html)

given the rethinking of pubs as a second device in [`%Gwqklkj0b2CBT5tPiz5170NWsPp3xiuLbOImEaG/e+4=.sha256`](https://viewer.scuttlebot.io/%25Gwqklkj0b2CBT5tPiz5170NWsPp3xiuLbOImEaG%2Fe%2B4%3D.sha256), should we continue to use the term "pub" when referring to a uxer's cloud device?

what about "bot", or is that too vague?

**Comment by ahdinosaur** [comment]
host?

**Comment by danalexilewis** [comment]
I quite liked pub - I think it had links to the British concept of a “public house”. Though with the way we are imagining pubs will be used it feels less akin to this. So I get why it feels off.

Brainstorm:

 - node
 - device
 - public device
 - hosted device
 - facade
 - remote
 - remote device
 - avatar

More boat analogies:

 - buoy (I like this)
 - dock
 - pontoon
 - port
 - berth
 - anchor

:)

**Comment by danalexilewis** [comment]
What’s nice about buoy is that you may put a buoy somehwhere - and it’s yours. But others can use it/interact with it.

It’s like a thing that’s yours that you leave in the ocean and others benefit from. In other words the network of bouys are mutually beneficially to all boats

**Comment by ahdinosaur** [comment]
for our code, i think i'm keen to use `pub` to refer to each uxer's server instance and `hub` to refer to the swarm (and provider services). we can always change later but i think these terms are good for meow.

**Comment by ahdinosaur** [comment]
renamed sub-projects as `buttpub` or `butthub` to reflect the naming.
